version: '2'

services:
  golru:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      PORT: "8080"
      PORT_GRPC: "50051"
      PROTOCOL: http
      APP_NAME: golru
      SERVICE_NAME: service1
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - mynet

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d transactions -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    networks:
      - mynet
  
  prometheus:
    image: 'prom/prometheus:v2.23.0'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mynet
  
  jaeger:
    image: jaegertracing/all-in-one:1.21
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"        
    networks:
      - mynet
       
networks:
  mynet:
