apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "generation.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "generation.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "generation.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "generation.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "generation.fullname" . }}
      labels: {{ include "generation.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: {{ include "generation.fullname" . }}-config-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |-
            ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
            cat > /var/run/generation/config.yaml << EOD
            data-dir: /var/run/generation/data
            rpc-port: {{.Values.rpcPort}}
            # Make sure the following three key-values are on one line each in
            # your code. I split them across multiple lines to fit them in
            # for the book.
            bind-addr: "$HOSTNAME.generation.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"
            bootstrap: $([ $ID = 0 ] && echo true || echo false)
            $([ $ID != 0 ] && echo 'start-join-addrs: "generation-0.generation.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}"') 
            EOD
        volumeMounts:
        - name: datadir
          mountPath: /var/run/generation
      containers:
      - name: {{ include "generation.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.rpcPort }}
          name: rpc
        - containerPort: {{ .Values.serfPort }}
          name: serf
        args:
        - --config-file=/var/run/generation/config.yaml
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
          initialDelaySeconds: 30
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
          initialDelaySeconds: 30
        volumeMounts:
        - name: datadir
          mountPath: /var/run/generation
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}

